#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by panos on 11/29/18
# IDE: PyCharm
"""
request_body stores the headers and params to request
"""
import time

request_body = [
    {
        'headers': {
            'Host': 'aweme.snssdk.com',
            'Accept': '*/*',
            'User-Agent': 'Aweme/1.8.2 (iPhone; iOS 12.0.1; Scale/2.00)',
            'Accept-Language': 'en-AU;q=1, zh-Hans-AU;q=0.9, ja-JP;q=0.8, zh-Hant-HK;q=0.7',
        },
        'params':
            (
                ('iid', '32518751301'),
                ('device_id', '52264655071'),
                ('os_api', '18'),
                ('app_name', 'aweme'),
                ('channel', 'App Store'),
                ('idfa', '00000000-0000-0000-0000-000000000000'),
                ('device_platform', 'iphone'),
                ('build_number', '18210'),
                ('vid', '7CDE9E67-169C-4609-A2B6-59A8B05EF0C9'),
                ('openudid', '14c8eae754bdb4d8c0ee0362159c966615bc238a'),
                ('device_type', 'iPhone8,4'),
                ('app_version', '1.8.2'),
                ('version_code', '1.8.2'),
                ('os_version', '12.0.1'),
                ('screen_width', '640'),
                ('aid', '1128'),
                ('ac', 'WIFI'),
                ('count', '6'),
                ('feed_style', '0'),
                ('filter_warn', '0'),
                ('max_cursor', '0'),
                ('pull_type', '2'),
                ('type', '0'),
                ('volume', '0.06'),
                ('ts', int(time.time())),
            ),
        'is_iphone': True,
    },
    {
        'headers': {
            'Accept-Encoding': 'gzip',
            'sdk-version': '1',
            'Host': 'api.amemv.com',
            'Connection': 'Keep-Alive',
            'User-Agent': 'okhttp/3.10.0.1',
        },
        'params': (('type', '0'),
                   ('max_cursor', '0'),
                   ('min_cursor', '-1'),
                   ('count', '6'),
                   ('volume', '0.0'),
                   ('pull_type', '2'),
                   ('need_relieve_aweme', '0'),
                   ('filter_warn', '0'),
                   ('req_from', ''),
                   ('is_cold_start', '0'),
                   ('ts', int(time.time())),
                   ('app_type', 'normal'),
                   ('openudid', '9f82e969a8d51760'),
                   ('version_name', '2.6.0'),
                   ('device_type', 'CHM-TL00H'),
                   ('ssmix', 'a'),
                   ('iid', '43773673657'),
                   ('os_api', '19'),
                   ('device_id', '56916873963'),
                   ('resolution', '720*1280'),
                   ('device_brand', 'Honor'),
                   ('aid', '1128'),
                   ('manifest_version_code', '260'),
                   ('app_name', 'aweme'),
                   ('_rticket', '1541043164150'),
                   ('os_version', '4.4.4'),
                   ('device_platform', 'android'),
                   ('version_code', '260'),
                   ('update_version_code', '2602'),
                   ('ac', 'wifi'),
                   ('dpi', '320'),
                   ('uuid', '866329027439476'),
                   ('language', 'zh'),
                   ('channel', 'update'),)
    },
    {
        'headers': {
            'Accept-Encoding': 'gzip',
            'Host': 'aweme.snssdk.com',
            'Connection': 'Keep-Alive',
            'User-Agent': 'okhttp/3.7.0.6',
        },
        'params': (('type', '0'),
                   ('max_cursor', '0'),
                   ('min_cursor', '-1'),
                   ('count', '6'),
                   ('volume', '0.7333333333333333'),
                   ('pull_type', '2'),
                   ('need_relieve_aweme', '0'),
                   ('filter_warn', '0'),
                   ('req_from', ''),
                   ('is_cold_start', '0'),
                   ('ts', int(time.time())),
                   ('app_type', 'normal'),
                   ('openudid', '5f5cd7cc3e681b11'),
                   ('version_name', '2.3.0'),
                   ('device_type', 'CHM-TL00H'),
                   ('ssmix', 'a'),
                   ('iid', '49085256189'),
                   ('os_api', '19'),
                   ('device_id', '58832986505'),
                   ('resolution', '720*1280'),
                   ('device_brand', 'Honor'),
                   ('aid', '1128'),
                   ('manifest_version_code', '230'),
                   ('app_name', 'aweme'),
                   ('_rticket', '1541044398300'),
                   ('os_version', '4.4.4'),
                   ('device_platform', 'android'),
                   ('version_code', '230'),
                   ('update_version_code', '2302'),
                   ('ac', 'wifi'),
                   ('dpi', '320'),
                   ('uuid', '604775554446257'),
                   ('language', 'zh'),
                   ('channel', 'aweGW'),)
    },
    {
        'headers': {
            'Accept-Encoding': 'gzip',
            'Host': 'api.amemv.com',
            'Connection': 'Keep-Alive',
            'User-Agent': 'okhttp/3.7.0.6',
        },
        'params': (('type', '0'),
                   ('max_cursor', '0'),
                   ('min_cursor', '-1'),
                   ('count', '6'),
                   ('volume', '0.7333333333333333'),
                   ('pull_type', '2'),
                   ('need_relieve_aweme', '0'),
                   ('filter_warn', '0'),
                   ('req_from', ''),
                   ('is_cold_start', '1'),
                   ('ts', int(time.time())),
                   ('app_type', 'normal'),
                   ('openudid', 'f7c889c513b43b5b'),
                   ('version_name', '2.3.0'),
                   ('device_type', 'CHM-TL00H'),
                   ('ssmix', 'a'),
                   ('iid', '49104696336'),
                   ('os_api', '19'),
                   ('device_id', '58835868353'),
                   ('resolution', '720*1280'),
                   ('device_brand', 'Honor'),
                   ('aid', '1128'),
                   ('manifest_version_code', '230'),
                   ('app_name', 'aweme'),
                   ('_rticket', '1541050977405'),
                   ('os_version', '4.4.4'),
                   ('device_platform', 'android'),
                   ('version_code', '230'),
                   ('update_version_code', '2302'),
                   ('ac', 'wifi'),
                   ('dpi', '320'),
                   ('uuid', '149173306296582'),
                   ('language', 'zh'),
                   ('channel', 'aweGW'))
    }
]

